server:
  port: 10001
spring:
  datasource:
    url: jdbc:h2:file:~/biblioteca
    driverClassName: org.h2.Driver
    username: alekhya
    password: ali

management:
  cloudfoundry:
    skip-ssl-validation: true

info:
  name: Spring Sample Application
  description: Welcome to Bibileoteca